config/routes.rb
T::Application.routes.draw do

  resources :contacts

root :to => 'contacts#index'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :name, :phone
  validates :phone, :length => {:minimum=>7}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end
  def index
    @contacts = Contact.all
  end
  def show
    @contact = Contact.find(params[:id])
  end
  def create
    @contact = Contact.new(params[:contact])
    @contact.save
    redirect_to :action => :show, :id => @contact.id
  end
  def edit
    @contact = Contact.find params[:id]
  end
  def update
    @contact = Contact.find params[:id]
    if @contact.update_attributes(params[:contact])
      redirect_to :action => :show, :id => @contact.id
    else
      render :action => 'edit'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
  def title
    "#{controller.action_name.humanize} | #{controller.controller_name.humanize}"
  end
end

app/views/contacts/_form.html.haml
= form_for @contact do |f|
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :phone
    %br/
    = f.text_field :phone
  .action
    = f.submit

app/views/contacts/edit.html.haml
%h1 Edit
= render 'form'

app/views/contacts/index.html.haml
%div
  %h1="This is Haml" 
#uldiv
  %ul
    - @contacts.each do |c|
      %li= raw c.name+link_to('Edit',edit_contact_path(c))

app/views/contacts/new.html.erb
<%= form_for @contact do |f| %>
  <% if @contact.errors.any? %>
    <div id="errorExplanation">
      <h2> <% pluralize(@contact.errors.count,"error") %> prohibited this post from being saved: </h2>
      <ul>
        <% @contact.errors.full_messages.each do |msg|%>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
  <%=f.label :name %><br/>
  <%=f.text_field :name%>
  </p>
  <p>
  <p>
  <%=f.label :phone%><br/>
  <%=f.text_field :phone%>
  </p>
  <%=f.submit %>
  </p>
<% end %>

app/views/contacts/show.html.erb
<div>
  <ul>
    <li><%= @contact.name %></li>
    <li><%= @contact.phone%></li>
    <li><%=@contact.name+link_to('Edit',edit_contact_path(@contact))%></li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%=title%></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>